"""
Theme Styles
=============
10 UI styles that control the visual shape/form of the interface.
Each style defines dimensions, border-radius, padding, spacing, and visual effects.
Styles are independent of colors (handled by palettes).
"""


STYLE_DEFINITIONS = {
    "modern": {
        "display_name": "حديث (Modern)",
        "description": "Material Design 3 - Rounded, shadows, spacious",
        "icon": "fa5s.layer-group",
        "border_radius_sm": 8,
        "border_radius_md": 12,
        "border_radius_lg": 16,
        "border_radius_xl": 20,
        "border_radius_pill": 24,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "4px 8px",
        "padding_sm": "8px 16px",
        "padding_md": "12px 24px",
        "padding_lg": "16px 32px",
        "padding_input": "10px 14px",
        "spacing_xs": 4,
        "spacing_sm": 8,
        "spacing_md": 12,
        "spacing_lg": 16,
        "spacing_xl": 24,
        "button_height": 40,
        "input_height": 42,
        "header_height": 48,
        "item_padding": "10px",
        "table_cell_padding": "10px 12px",
        "table_header_padding": "12px 14px",
        "card_padding": 16,
        "dialog_padding": 24,
        "menu_item_padding": "10px 30px",
        "menu_item_radius": 6,
        "toolbar_padding": 6,
        "toolbar_btn_padding": "8px 16px",
        "scrollbar_width": 10,
        "scrollbar_radius": 5,
        "scrollbar_min": 30,
        "font_scale": 1.0,
        "use_shadows": True,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 1,
    },

    "fluent": {
        "display_name": "أنيق (Fluent)",
        "description": "Microsoft Fluent UI - Subtle transparency, refined",
        "icon": "fa5s.wind",
        "border_radius_sm": 6,
        "border_radius_md": 8,
        "border_radius_lg": 12,
        "border_radius_xl": 16,
        "border_radius_pill": 20,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "4px 8px",
        "padding_sm": "7px 14px",
        "padding_md": "10px 20px",
        "padding_lg": "14px 28px",
        "padding_input": "9px 12px",
        "spacing_xs": 4,
        "spacing_sm": 7,
        "spacing_md": 10,
        "spacing_lg": 14,
        "spacing_xl": 20,
        "button_height": 36,
        "input_height": 38,
        "header_height": 44,
        "item_padding": "8px",
        "table_cell_padding": "8px 10px",
        "table_header_padding": "10px 12px",
        "card_padding": 14,
        "dialog_padding": 20,
        "menu_item_padding": "8px 24px",
        "menu_item_radius": 5,
        "toolbar_padding": 5,
        "toolbar_btn_padding": "7px 14px",
        "scrollbar_width": 8,
        "scrollbar_radius": 4,
        "scrollbar_min": 28,
        "font_scale": 1.0,
        "use_shadows": True,
        "use_gradients": False,
        "use_transparency": True,
        "separator_height": 1,
    },

    "flat": {
        "display_name": "مسطح (Flat)",
        "description": "Metro UI - No shadows, sharp, clean",
        "icon": "fa5s.square",
        "border_radius_sm": 0,
        "border_radius_md": 0,
        "border_radius_lg": 2,
        "border_radius_xl": 2,
        "border_radius_pill": 0,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "4px 8px",
        "padding_sm": "8px 16px",
        "padding_md": "10px 20px",
        "padding_lg": "14px 28px",
        "padding_input": "9px 12px",
        "spacing_xs": 4,
        "spacing_sm": 8,
        "spacing_md": 10,
        "spacing_lg": 14,
        "spacing_xl": 20,
        "button_height": 36,
        "input_height": 36,
        "header_height": 42,
        "item_padding": "8px",
        "table_cell_padding": "8px 10px",
        "table_header_padding": "10px 12px",
        "card_padding": 14,
        "dialog_padding": 20,
        "menu_item_padding": "8px 24px",
        "menu_item_radius": 0,
        "toolbar_padding": 4,
        "toolbar_btn_padding": "7px 14px",
        "scrollbar_width": 10,
        "scrollbar_radius": 0,
        "scrollbar_min": 30,
        "font_scale": 1.0,
        "use_shadows": False,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 2,
    },

    "glass": {
        "display_name": "زجاجي (Glassmorphism)",
        "description": "Apple/iOS - Transparency, glowing borders",
        "icon": "fa5s.glass-whiskey",
        "border_radius_sm": 10,
        "border_radius_md": 14,
        "border_radius_lg": 18,
        "border_radius_xl": 22,
        "border_radius_pill": 28,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "5px 10px",
        "padding_sm": "8px 18px",
        "padding_md": "12px 26px",
        "padding_lg": "16px 34px",
        "padding_input": "10px 14px",
        "spacing_xs": 5,
        "spacing_sm": 8,
        "spacing_md": 14,
        "spacing_lg": 18,
        "spacing_xl": 26,
        "button_height": 40,
        "input_height": 42,
        "header_height": 48,
        "item_padding": "10px",
        "table_cell_padding": "10px 12px",
        "table_header_padding": "12px 14px",
        "card_padding": 18,
        "dialog_padding": 24,
        "menu_item_padding": "10px 28px",
        "menu_item_radius": 8,
        "toolbar_padding": 6,
        "toolbar_btn_padding": "8px 16px",
        "scrollbar_width": 8,
        "scrollbar_radius": 4,
        "scrollbar_min": 28,
        "font_scale": 1.0,
        "use_shadows": True,
        "use_gradients": True,
        "use_transparency": True,
        "separator_height": 1,
    },

    "neumorphism": {
        "display_name": "بارز (Neumorphism)",
        "description": "Soft UI - Embossed/inset, soft look",
        "icon": "fa5s.circle",
        "border_radius_sm": 12,
        "border_radius_md": 16,
        "border_radius_lg": 20,
        "border_radius_xl": 24,
        "border_radius_pill": 30,
        "border_width": 0,
        "border_width_focus": 2,
        "padding_xs": "6px 10px",
        "padding_sm": "10px 18px",
        "padding_md": "14px 26px",
        "padding_lg": "18px 34px",
        "padding_input": "12px 16px",
        "spacing_xs": 6,
        "spacing_sm": 10,
        "spacing_md": 14,
        "spacing_lg": 18,
        "spacing_xl": 28,
        "button_height": 44,
        "input_height": 44,
        "header_height": 50,
        "item_padding": "12px",
        "table_cell_padding": "12px 14px",
        "table_header_padding": "14px 16px",
        "card_padding": 20,
        "dialog_padding": 28,
        "menu_item_padding": "12px 30px",
        "menu_item_radius": 10,
        "toolbar_padding": 8,
        "toolbar_btn_padding": "10px 18px",
        "scrollbar_width": 10,
        "scrollbar_radius": 5,
        "scrollbar_min": 32,
        "font_scale": 1.0,
        "use_shadows": True,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 0,
    },

    "rounded": {
        "display_name": "مدور (Rounded)",
        "description": "Spotify/Slack - Everything round, pill-shaped buttons",
        "icon": "fa5s.circle-notch",
        "border_radius_sm": 14,
        "border_radius_md": 18,
        "border_radius_lg": 22,
        "border_radius_xl": 28,
        "border_radius_pill": 50,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "5px 12px",
        "padding_sm": "8px 18px",
        "padding_md": "12px 28px",
        "padding_lg": "16px 36px",
        "padding_input": "10px 16px",
        "spacing_xs": 5,
        "spacing_sm": 8,
        "spacing_md": 14,
        "spacing_lg": 18,
        "spacing_xl": 26,
        "button_height": 42,
        "input_height": 42,
        "header_height": 48,
        "item_padding": "10px",
        "table_cell_padding": "10px 14px",
        "table_header_padding": "12px 16px",
        "card_padding": 18,
        "dialog_padding": 24,
        "menu_item_padding": "10px 28px",
        "menu_item_radius": 14,
        "toolbar_padding": 6,
        "toolbar_btn_padding": "8px 18px",
        "scrollbar_width": 10,
        "scrollbar_radius": 5,
        "scrollbar_min": 30,
        "font_scale": 1.0,
        "use_shadows": True,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 1,
    },

    "compact": {
        "display_name": "مضغوط (Compact)",
        "description": "IDE/Bloomberg - Dense, small elements, data-friendly",
        "icon": "fa5s.compress-alt",
        "border_radius_sm": 3,
        "border_radius_md": 4,
        "border_radius_lg": 6,
        "border_radius_xl": 8,
        "border_radius_pill": 12,
        "border_width": 1,
        "border_width_focus": 1,
        "padding_xs": "2px 4px",
        "padding_sm": "4px 8px",
        "padding_md": "6px 12px",
        "padding_lg": "8px 16px",
        "padding_input": "5px 8px",
        "spacing_xs": 2,
        "spacing_sm": 4,
        "spacing_md": 6,
        "spacing_lg": 8,
        "spacing_xl": 12,
        "button_height": 28,
        "input_height": 28,
        "header_height": 32,
        "item_padding": "4px",
        "table_cell_padding": "4px 6px",
        "table_header_padding": "6px 8px",
        "card_padding": 8,
        "dialog_padding": 12,
        "menu_item_padding": "5px 16px",
        "menu_item_radius": 3,
        "toolbar_padding": 2,
        "toolbar_btn_padding": "4px 8px",
        "scrollbar_width": 8,
        "scrollbar_radius": 4,
        "scrollbar_min": 20,
        "font_scale": 0.9,
        "use_shadows": False,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 1,
    },

    "classic": {
        "display_name": "كلاسيكي (Classic)",
        "description": "Windows Forms - Traditional, square, familiar",
        "icon": "fa5s.desktop",
        "border_radius_sm": 2,
        "border_radius_md": 3,
        "border_radius_lg": 4,
        "border_radius_xl": 6,
        "border_radius_pill": 3,
        "border_width": 1,
        "border_width_focus": 2,
        "padding_xs": "3px 6px",
        "padding_sm": "6px 12px",
        "padding_md": "8px 18px",
        "padding_lg": "12px 24px",
        "padding_input": "7px 10px",
        "spacing_xs": 3,
        "spacing_sm": 6,
        "spacing_md": 8,
        "spacing_lg": 12,
        "spacing_xl": 18,
        "button_height": 32,
        "input_height": 32,
        "header_height": 36,
        "item_padding": "6px",
        "table_cell_padding": "6px 8px",
        "table_header_padding": "8px 10px",
        "card_padding": 12,
        "dialog_padding": 16,
        "menu_item_padding": "6px 20px",
        "menu_item_radius": 2,
        "toolbar_padding": 4,
        "toolbar_btn_padding": "6px 12px",
        "scrollbar_width": 14,
        "scrollbar_radius": 0,
        "scrollbar_min": 24,
        "font_scale": 1.0,
        "use_shadows": False,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 1,
    },

    "elegant": {
        "display_name": "راقي (Elegant)",
        "description": "Notion/Linear - Thin borders, whitespace, refined",
        "icon": "fa5s.feather-alt",
        "border_radius_sm": 6,
        "border_radius_md": 8,
        "border_radius_lg": 10,
        "border_radius_xl": 14,
        "border_radius_pill": 20,
        "border_width": 1,
        "border_width_focus": 1,
        "padding_xs": "5px 10px",
        "padding_sm": "9px 18px",
        "padding_md": "13px 26px",
        "padding_lg": "18px 36px",
        "padding_input": "11px 16px",
        "spacing_xs": 6,
        "spacing_sm": 10,
        "spacing_md": 16,
        "spacing_lg": 22,
        "spacing_xl": 32,
        "button_height": 40,
        "input_height": 42,
        "header_height": 48,
        "item_padding": "12px",
        "table_cell_padding": "12px 16px",
        "table_header_padding": "14px 18px",
        "card_padding": 22,
        "dialog_padding": 30,
        "menu_item_padding": "12px 30px",
        "menu_item_radius": 6,
        "toolbar_padding": 8,
        "toolbar_btn_padding": "9px 18px",
        "scrollbar_width": 6,
        "scrollbar_radius": 3,
        "scrollbar_min": 28,
        "font_scale": 1.05,
        "use_shadows": False,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 1,
    },

    "bold": {
        "display_name": "عريض (Bold)",
        "description": "Dashboard Pro - Large elements, thick borders, bold fonts",
        "icon": "fa5s.bold",
        "border_radius_sm": 8,
        "border_radius_md": 10,
        "border_radius_lg": 14,
        "border_radius_xl": 18,
        "border_radius_pill": 24,
        "border_width": 2,
        "border_width_focus": 3,
        "padding_xs": "6px 12px",
        "padding_sm": "10px 20px",
        "padding_md": "14px 30px",
        "padding_lg": "18px 38px",
        "padding_input": "12px 16px",
        "spacing_xs": 6,
        "spacing_sm": 10,
        "spacing_md": 16,
        "spacing_lg": 22,
        "spacing_xl": 30,
        "button_height": 46,
        "input_height": 46,
        "header_height": 54,
        "item_padding": "14px",
        "table_cell_padding": "14px 16px",
        "table_header_padding": "16px 18px",
        "card_padding": 22,
        "dialog_padding": 28,
        "menu_item_padding": "12px 30px",
        "menu_item_radius": 8,
        "toolbar_padding": 8,
        "toolbar_btn_padding": "10px 20px",
        "scrollbar_width": 14,
        "scrollbar_radius": 7,
        "scrollbar_min": 36,
        "font_scale": 1.1,
        "use_shadows": True,
        "use_gradients": False,
        "use_transparency": False,
        "separator_height": 2,
    },
}


def get_style(style_name: str) -> dict:
    """Get style definition. Falls back to modern."""
    return STYLE_DEFINITIONS.get(style_name, STYLE_DEFINITIONS["modern"])


def get_all_style_names() -> list:
    """Get all available style names."""
    return list(STYLE_DEFINITIONS.keys())


def get_style_display_name(style_name: str) -> str:
    """Get display name for a style."""
    style = STYLE_DEFINITIONS.get(style_name)
    return style["display_name"] if style else style_name


def get_style_description(style_name: str) -> str:
    """Get description for a style."""
    style = STYLE_DEFINITIONS.get(style_name)
    return style.get("description", "") if style else ""
