"""
Theme Palettes
==============
All INTEGRA color themes defined as simple dictionaries.
24 palettes (16 dark + 8 light) - single source of truth for all colors.

To add a new theme: just add a new entry to THEME_PALETTES dict.
"""

# ─── Palette structure ────────────────────────────────────────
# Each palette must define these keys:
#   display_name, icon, category, is_dark
#   bg_main, bg_card, bg_input, bg_header, bg_dialog, bg_sidebar, bg_hover, bg_tooltip
#   text_primary, text_secondary, text_muted, text_on_primary
#   primary, primary_hover, primary_pressed, primary_light
#   accent, success, warning, danger, info
#   border, border_light, border_focus
#   header_bg, header_text, header_border
#   scrollbar_bg, scrollbar_handle, scrollbar_hover
#   disabled_bg, disabled_text
#   selection_bg, selection_text
#   shadow_color

THEME_PALETTES = {
    # ══════════════════════════════════════════════════
    #  DARK THEMES
    # ══════════════════════════════════════════════════

    "dark": {
        "display_name": "داكن (Dark)",
        "icon": "fa5s.moon",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#0f172a",
        "bg_card": "#1e293b",
        "bg_input": "#1e293b",
        "bg_header": "#1e293b",
        "bg_dialog": "#1e293b",
        "bg_sidebar": "#0f172a",
        "bg_hover": "#273548",
        "bg_tooltip": "#334155",
        "text_primary": "#f1f5f9",
        "text_secondary": "#94a3b8",
        "text_muted": "#64748b",
        "text_on_primary": "#ffffff",
        "primary": "#2563eb",
        "primary_hover": "#3b82f6",
        "primary_pressed": "#1d4ed8",
        "primary_light": "#1e3a5f",
        "accent": "#06b6d4",
        "success": "#10b981",
        "warning": "#f59e0b",
        "danger": "#ef4444",
        "info": "#3b82f6",
        "border": "#334155",
        "border_light": "#475569",
        "border_focus": "#2563eb",
        "header_bg": "#1e293b",
        "header_text": "#f1f5f9",
        "header_border": "#2563eb",
        "scrollbar_bg": "#1e293b",
        "scrollbar_handle": "#475569",
        "scrollbar_hover": "#2563eb",
        "disabled_bg": "#0f172a",
        "disabled_text": "#64748b",
        "selection_bg": "#2563eb",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "midnight": {
        "display_name": "منتصف الليل (Midnight)",
        "icon": "fa5s.star",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#0a0e1a",
        "bg_card": "#121829",
        "bg_input": "#121829",
        "bg_header": "#121829",
        "bg_dialog": "#121829",
        "bg_sidebar": "#0a0e1a",
        "bg_hover": "#1a2038",
        "bg_tooltip": "#1a237e",
        "text_primary": "#e8eaf6",
        "text_secondary": "#9fa8da",
        "text_muted": "#5c6bc0",
        "text_on_primary": "#ffffff",
        "primary": "#536dfe",
        "primary_hover": "#8c9eff",
        "primary_pressed": "#304ffe",
        "primary_light": "#1a237e",
        "accent": "#448aff",
        "success": "#69f0ae",
        "warning": "#ffd740",
        "danger": "#ff5252",
        "info": "#448aff",
        "border": "#1a237e",
        "border_light": "#283593",
        "border_focus": "#536dfe",
        "header_bg": "#121829",
        "header_text": "#e8eaf6",
        "header_border": "#536dfe",
        "scrollbar_bg": "#121829",
        "scrollbar_handle": "#283593",
        "scrollbar_hover": "#536dfe",
        "disabled_bg": "#0a0e1a",
        "disabled_text": "#5c6bc0",
        "selection_bg": "#536dfe",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 100)",
    },

    "nord": {
        "display_name": "شمالي (Nord)",
        "icon": "fa5s.snowflake",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#2e3440",
        "bg_card": "#3b4252",
        "bg_input": "#3b4252",
        "bg_header": "#3b4252",
        "bg_dialog": "#3b4252",
        "bg_sidebar": "#2e3440",
        "bg_hover": "#434c5e",
        "bg_tooltip": "#4c566a",
        "text_primary": "#eceff4",
        "text_secondary": "#d8dee9",
        "text_muted": "#81a1c1",
        "text_on_primary": "#2e3440",
        "primary": "#88c0d0",
        "primary_hover": "#8fbcbb",
        "primary_pressed": "#5e81ac",
        "primary_light": "#3b4f5e",
        "accent": "#81a1c1",
        "success": "#a3be8c",
        "warning": "#ebcb8b",
        "danger": "#bf616a",
        "info": "#81a1c1",
        "border": "#434c5e",
        "border_light": "#4c566a",
        "border_focus": "#88c0d0",
        "header_bg": "#3b4252",
        "header_text": "#eceff4",
        "header_border": "#88c0d0",
        "scrollbar_bg": "#3b4252",
        "scrollbar_handle": "#4c566a",
        "scrollbar_hover": "#88c0d0",
        "disabled_bg": "#2e3440",
        "disabled_text": "#4c566a",
        "selection_bg": "#88c0d0",
        "selection_text": "#2e3440",
        "shadow_color": "rgba(0, 0, 0, 60)",
    },

    "dracula": {
        "display_name": "دراكولا (Dracula)",
        "icon": "fa5s.ghost",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#282a36",
        "bg_card": "#44475a",
        "bg_input": "#44475a",
        "bg_header": "#44475a",
        "bg_dialog": "#44475a",
        "bg_sidebar": "#282a36",
        "bg_hover": "#4e5166",
        "bg_tooltip": "#6272a4",
        "text_primary": "#f8f8f2",
        "text_secondary": "#bd93f9",
        "text_muted": "#6272a4",
        "text_on_primary": "#282a36",
        "primary": "#bd93f9",
        "primary_hover": "#caa9fa",
        "primary_pressed": "#9b6dff",
        "primary_light": "#3d3560",
        "accent": "#8be9fd",
        "success": "#50fa7b",
        "warning": "#f1fa8c",
        "danger": "#ff5555",
        "info": "#8be9fd",
        "border": "#44475a",
        "border_light": "#6272a4",
        "border_focus": "#bd93f9",
        "header_bg": "#44475a",
        "header_text": "#f8f8f2",
        "header_border": "#bd93f9",
        "scrollbar_bg": "#282a36",
        "scrollbar_handle": "#6272a4",
        "scrollbar_hover": "#bd93f9",
        "disabled_bg": "#282a36",
        "disabled_text": "#6272a4",
        "selection_bg": "#bd93f9",
        "selection_text": "#282a36",
        "shadow_color": "rgba(0, 0, 0, 70)",
    },

    "monokai": {
        "display_name": "مونوكاي (Monokai)",
        "icon": "fa5s.code",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#272822",
        "bg_card": "#3e3d32",
        "bg_input": "#3e3d32",
        "bg_header": "#3e3d32",
        "bg_dialog": "#3e3d32",
        "bg_sidebar": "#272822",
        "bg_hover": "#49483e",
        "bg_tooltip": "#75715e",
        "text_primary": "#f8f8f2",
        "text_secondary": "#e6db74",
        "text_muted": "#75715e",
        "text_on_primary": "#272822",
        "primary": "#a6e22e",
        "primary_hover": "#b6f23e",
        "primary_pressed": "#86c20e",
        "primary_light": "#3a4a1a",
        "accent": "#66d9ef",
        "success": "#a6e22e",
        "warning": "#e6db74",
        "danger": "#f92672",
        "info": "#66d9ef",
        "border": "#49483e",
        "border_light": "#75715e",
        "border_focus": "#a6e22e",
        "header_bg": "#3e3d32",
        "header_text": "#f8f8f2",
        "header_border": "#a6e22e",
        "scrollbar_bg": "#272822",
        "scrollbar_handle": "#75715e",
        "scrollbar_hover": "#a6e22e",
        "disabled_bg": "#272822",
        "disabled_text": "#75715e",
        "selection_bg": "#a6e22e",
        "selection_text": "#272822",
        "shadow_color": "rgba(0, 0, 0, 70)",
    },

    "gruvbox_dark": {
        "display_name": "جروفبوكس داكن (Gruvbox Dark)",
        "icon": "fa5s.tree",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#282828",
        "bg_card": "#3c3836",
        "bg_input": "#3c3836",
        "bg_header": "#3c3836",
        "bg_dialog": "#3c3836",
        "bg_sidebar": "#282828",
        "bg_hover": "#504945",
        "bg_tooltip": "#665c54",
        "text_primary": "#ebdbb2",
        "text_secondary": "#d5c4a1",
        "text_muted": "#928374",
        "text_on_primary": "#ebdbb2",
        "primary": "#458588",
        "primary_hover": "#83a598",
        "primary_pressed": "#076678",
        "primary_light": "#2a3d3e",
        "accent": "#689d6a",
        "success": "#b8bb26",
        "warning": "#fabd2f",
        "danger": "#fb4934",
        "info": "#83a598",
        "border": "#504945",
        "border_light": "#665c54",
        "border_focus": "#458588",
        "header_bg": "#3c3836",
        "header_text": "#ebdbb2",
        "header_border": "#458588",
        "scrollbar_bg": "#3c3836",
        "scrollbar_handle": "#665c54",
        "scrollbar_hover": "#458588",
        "disabled_bg": "#282828",
        "disabled_text": "#928374",
        "selection_bg": "#458588",
        "selection_text": "#ebdbb2",
        "shadow_color": "rgba(0, 0, 0, 60)",
    },

    "solarized_dark": {
        "display_name": "سولارايزد داكن (Solarized Dark)",
        "icon": "fa5s.sun",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#002b36",
        "bg_card": "#073642",
        "bg_input": "#073642",
        "bg_header": "#073642",
        "bg_dialog": "#073642",
        "bg_sidebar": "#002b36",
        "bg_hover": "#0a4050",
        "bg_tooltip": "#586e75",
        "text_primary": "#fdf6e3",
        "text_secondary": "#eee8d5",
        "text_muted": "#839496",
        "text_on_primary": "#fdf6e3",
        "primary": "#268bd2",
        "primary_hover": "#2aa198",
        "primary_pressed": "#0d6ebd",
        "primary_light": "#0a3d5c",
        "accent": "#2aa198",
        "success": "#859900",
        "warning": "#b58900",
        "danger": "#dc322f",
        "info": "#268bd2",
        "border": "#586e75",
        "border_light": "#657b83",
        "border_focus": "#268bd2",
        "header_bg": "#073642",
        "header_text": "#fdf6e3",
        "header_border": "#268bd2",
        "scrollbar_bg": "#073642",
        "scrollbar_handle": "#586e75",
        "scrollbar_hover": "#268bd2",
        "disabled_bg": "#002b36",
        "disabled_text": "#586e75",
        "selection_bg": "#268bd2",
        "selection_text": "#fdf6e3",
        "shadow_color": "rgba(0, 0, 0, 70)",
    },

    "tokyo_night": {
        "display_name": "ليلة طوكيو (Tokyo Night)",
        "icon": "fa5s.city",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1a1b26",
        "bg_card": "#24283b",
        "bg_input": "#24283b",
        "bg_header": "#24283b",
        "bg_dialog": "#24283b",
        "bg_sidebar": "#1a1b26",
        "bg_hover": "#2f3348",
        "bg_tooltip": "#414868",
        "text_primary": "#c0caf5",
        "text_secondary": "#a9b1d6",
        "text_muted": "#565f89",
        "text_on_primary": "#1a1b26",
        "primary": "#7aa2f7",
        "primary_hover": "#89b4fa",
        "primary_pressed": "#5d7ee6",
        "primary_light": "#2a3358",
        "accent": "#bb9af7",
        "success": "#9ece6a",
        "warning": "#e0af68",
        "danger": "#f7768e",
        "info": "#7aa2f7",
        "border": "#3b4261",
        "border_light": "#414868",
        "border_focus": "#7aa2f7",
        "header_bg": "#24283b",
        "header_text": "#c0caf5",
        "header_border": "#7aa2f7",
        "scrollbar_bg": "#24283b",
        "scrollbar_handle": "#414868",
        "scrollbar_hover": "#7aa2f7",
        "disabled_bg": "#1a1b26",
        "disabled_text": "#565f89",
        "selection_bg": "#7aa2f7",
        "selection_text": "#1a1b26",
        "shadow_color": "rgba(0, 0, 0, 90)",
    },

    "catppuccin_mocha": {
        "display_name": "كابتشينو (Catppuccin Mocha)",
        "icon": "fa5s.coffee",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1e1e2e",
        "bg_card": "#313244",
        "bg_input": "#313244",
        "bg_header": "#313244",
        "bg_dialog": "#313244",
        "bg_sidebar": "#1e1e2e",
        "bg_hover": "#3a3c50",
        "bg_tooltip": "#585b70",
        "text_primary": "#cdd6f4",
        "text_secondary": "#bac2de",
        "text_muted": "#6c7086",
        "text_on_primary": "#1e1e2e",
        "primary": "#89b4fa",
        "primary_hover": "#b4d0fb",
        "primary_pressed": "#5e97f6",
        "primary_light": "#2a3352",
        "accent": "#cba6f7",
        "success": "#a6e3a1",
        "warning": "#f9e2af",
        "danger": "#f38ba8",
        "info": "#89b4fa",
        "border": "#45475a",
        "border_light": "#585b70",
        "border_focus": "#89b4fa",
        "header_bg": "#313244",
        "header_text": "#cdd6f4",
        "header_border": "#89b4fa",
        "scrollbar_bg": "#313244",
        "scrollbar_handle": "#585b70",
        "scrollbar_hover": "#89b4fa",
        "disabled_bg": "#1e1e2e",
        "disabled_text": "#6c7086",
        "selection_bg": "#89b4fa",
        "selection_text": "#1e1e2e",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "forest": {
        "display_name": "الغابة (Forest)",
        "icon": "fa5s.leaf",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1a2216",
        "bg_card": "#263020",
        "bg_input": "#263020",
        "bg_header": "#263020",
        "bg_dialog": "#263020",
        "bg_sidebar": "#1a2216",
        "bg_hover": "#2e4626",
        "bg_tooltip": "#3e5e33",
        "text_primary": "#d4e7c5",
        "text_secondary": "#a3c585",
        "text_muted": "#6b8f4e",
        "text_on_primary": "#ffffff",
        "primary": "#4caf50",
        "primary_hover": "#66bb6a",
        "primary_pressed": "#388e3c",
        "primary_light": "#1e3a1e",
        "accent": "#81c784",
        "success": "#a5d6a7",
        "warning": "#ffcc02",
        "danger": "#ef5350",
        "info": "#66bb6a",
        "border": "#2e4626",
        "border_light": "#3e5e33",
        "border_focus": "#4caf50",
        "header_bg": "#263020",
        "header_text": "#d4e7c5",
        "header_border": "#4caf50",
        "scrollbar_bg": "#263020",
        "scrollbar_handle": "#3e5e33",
        "scrollbar_hover": "#4caf50",
        "disabled_bg": "#1a2216",
        "disabled_text": "#6b8f4e",
        "selection_bg": "#4caf50",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 70)",
    },

    "ocean": {
        "display_name": "المحيط (Ocean)",
        "icon": "fa5s.water",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#0d1b2a",
        "bg_card": "#1b2838",
        "bg_input": "#1b2838",
        "bg_header": "#1b2838",
        "bg_dialog": "#1b2838",
        "bg_sidebar": "#0d1b2a",
        "bg_hover": "#1e3a50",
        "bg_tooltip": "#2c5068",
        "text_primary": "#e0f7fa",
        "text_secondary": "#80deea",
        "text_muted": "#4db6ac",
        "text_on_primary": "#ffffff",
        "primary": "#0097a7",
        "primary_hover": "#00bcd4",
        "primary_pressed": "#00838f",
        "primary_light": "#0a3545",
        "accent": "#26c6da",
        "success": "#66bb6a",
        "warning": "#ffca28",
        "danger": "#ef5350",
        "info": "#00bcd4",
        "border": "#1e3a50",
        "border_light": "#2c5068",
        "border_focus": "#0097a7",
        "header_bg": "#1b2838",
        "header_text": "#e0f7fa",
        "header_border": "#0097a7",
        "scrollbar_bg": "#1b2838",
        "scrollbar_handle": "#2c5068",
        "scrollbar_hover": "#0097a7",
        "disabled_bg": "#0d1b2a",
        "disabled_text": "#4db6ac",
        "selection_bg": "#0097a7",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "sunset": {
        "display_name": "الغروب (Sunset)",
        "icon": "fa5s.cloud-sun",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1f1315",
        "bg_card": "#2d1f22",
        "bg_input": "#2d1f22",
        "bg_header": "#2d1f22",
        "bg_dialog": "#2d1f22",
        "bg_sidebar": "#1f1315",
        "bg_hover": "#4a2c28",
        "bg_tooltip": "#5e3a35",
        "text_primary": "#fde8e0",
        "text_secondary": "#f5b7a5",
        "text_muted": "#b07060",
        "text_on_primary": "#ffffff",
        "primary": "#ff7043",
        "primary_hover": "#ff8a65",
        "primary_pressed": "#e64a19",
        "primary_light": "#4a2520",
        "accent": "#ffab91",
        "success": "#a5d6a7",
        "warning": "#ffe082",
        "danger": "#ef5350",
        "info": "#ff8a65",
        "border": "#4a2c28",
        "border_light": "#5e3a35",
        "border_focus": "#ff7043",
        "header_bg": "#2d1f22",
        "header_text": "#fde8e0",
        "header_border": "#ff7043",
        "scrollbar_bg": "#2d1f22",
        "scrollbar_handle": "#5e3a35",
        "scrollbar_hover": "#ff7043",
        "disabled_bg": "#1f1315",
        "disabled_text": "#b07060",
        "selection_bg": "#ff7043",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "rose": {
        "display_name": "وردي (Rose)",
        "icon": "fa5s.heart",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1a1118",
        "bg_card": "#2a1d26",
        "bg_input": "#2a1d26",
        "bg_header": "#2a1d26",
        "bg_dialog": "#2a1d26",
        "bg_sidebar": "#1a1118",
        "bg_hover": "#3e1f33",
        "bg_tooltip": "#5c2d47",
        "text_primary": "#fce4ec",
        "text_secondary": "#f8bbd0",
        "text_muted": "#ad6b8d",
        "text_on_primary": "#ffffff",
        "primary": "#e91e63",
        "primary_hover": "#f06292",
        "primary_pressed": "#c2185b",
        "primary_light": "#3e1530",
        "accent": "#f48fb1",
        "success": "#69f0ae",
        "warning": "#ffd54f",
        "danger": "#ff5252",
        "info": "#f06292",
        "border": "#3e1f33",
        "border_light": "#5c2d47",
        "border_focus": "#e91e63",
        "header_bg": "#2a1d26",
        "header_text": "#fce4ec",
        "header_border": "#e91e63",
        "scrollbar_bg": "#2a1d26",
        "scrollbar_handle": "#5c2d47",
        "scrollbar_hover": "#e91e63",
        "disabled_bg": "#1a1118",
        "disabled_text": "#ad6b8d",
        "selection_bg": "#e91e63",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "purple_rain": {
        "display_name": "مطر بنفسجي (Purple Rain)",
        "icon": "fa5s.cloud-rain",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1a0e2e",
        "bg_card": "#261542",
        "bg_input": "#261542",
        "bg_header": "#261542",
        "bg_dialog": "#261542",
        "bg_sidebar": "#1a0e2e",
        "bg_hover": "#38206a",
        "bg_tooltip": "#4a2d80",
        "text_primary": "#ede7f6",
        "text_secondary": "#ce93d8",
        "text_muted": "#8e6aad",
        "text_on_primary": "#ffffff",
        "primary": "#9c27b0",
        "primary_hover": "#ba68c8",
        "primary_pressed": "#7b1fa2",
        "primary_light": "#2e1548",
        "accent": "#e040fb",
        "success": "#69f0ae",
        "warning": "#ffd740",
        "danger": "#ff5252",
        "info": "#ba68c8",
        "border": "#38206a",
        "border_light": "#4a2d80",
        "border_focus": "#9c27b0",
        "header_bg": "#261542",
        "header_text": "#ede7f6",
        "header_border": "#9c27b0",
        "scrollbar_bg": "#261542",
        "scrollbar_handle": "#4a2d80",
        "scrollbar_hover": "#9c27b0",
        "disabled_bg": "#1a0e2e",
        "disabled_text": "#8e6aad",
        "selection_bg": "#9c27b0",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 90)",
    },

    "ember": {
        "display_name": "الجمر (Ember)",
        "icon": "fa5s.fire",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#1c1210",
        "bg_card": "#2c1e1a",
        "bg_input": "#2c1e1a",
        "bg_header": "#2c1e1a",
        "bg_dialog": "#2c1e1a",
        "bg_sidebar": "#1c1210",
        "bg_hover": "#4e342e",
        "bg_tooltip": "#6d4c41",
        "text_primary": "#fff3e0",
        "text_secondary": "#ffcc80",
        "text_muted": "#a1887f",
        "text_on_primary": "#ffffff",
        "primary": "#ff6d00",
        "primary_hover": "#ff9100",
        "primary_pressed": "#e65100",
        "primary_light": "#4a2800",
        "accent": "#ffab40",
        "success": "#66bb6a",
        "warning": "#ffc107",
        "danger": "#ff1744",
        "info": "#ff9100",
        "border": "#4e342e",
        "border_light": "#6d4c41",
        "border_focus": "#ff6d00",
        "header_bg": "#2c1e1a",
        "header_text": "#fff3e0",
        "header_border": "#ff6d00",
        "scrollbar_bg": "#2c1e1a",
        "scrollbar_handle": "#6d4c41",
        "scrollbar_hover": "#ff6d00",
        "disabled_bg": "#1c1210",
        "disabled_text": "#a1887f",
        "selection_bg": "#ff6d00",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    "arctic": {
        "display_name": "القطب (Arctic)",
        "icon": "fa5s.icicles",
        "category": "dark",
        "is_dark": True,
        "bg_main": "#0d1520",
        "bg_card": "#162030",
        "bg_input": "#162030",
        "bg_header": "#162030",
        "bg_dialog": "#162030",
        "bg_sidebar": "#0d1520",
        "bg_hover": "#1e3550",
        "bg_tooltip": "#2a4a68",
        "text_primary": "#e3f2fd",
        "text_secondary": "#90caf9",
        "text_muted": "#5c8db5",
        "text_on_primary": "#ffffff",
        "primary": "#42a5f5",
        "primary_hover": "#64b5f6",
        "primary_pressed": "#1e88e5",
        "primary_light": "#1a3550",
        "accent": "#80d8ff",
        "success": "#69f0ae",
        "warning": "#fff176",
        "danger": "#ef5350",
        "info": "#64b5f6",
        "border": "#1e3550",
        "border_light": "#2a4a68",
        "border_focus": "#42a5f5",
        "header_bg": "#162030",
        "header_text": "#e3f2fd",
        "header_border": "#42a5f5",
        "scrollbar_bg": "#162030",
        "scrollbar_handle": "#2a4a68",
        "scrollbar_hover": "#42a5f5",
        "disabled_bg": "#0d1520",
        "disabled_text": "#5c8db5",
        "selection_bg": "#42a5f5",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 80)",
    },

    # ══════════════════════════════════════════════════
    #  LIGHT THEMES
    # ══════════════════════════════════════════════════

    "light": {
        "display_name": "فاتح (Light)",
        "icon": "fa5s.sun",
        "category": "light",
        "is_dark": False,
        "bg_main": "#f8fafc",
        "bg_card": "#ffffff",
        "bg_input": "#ffffff",
        "bg_header": "#ffffff",
        "bg_dialog": "#ffffff",
        "bg_sidebar": "#f1f5f9",
        "bg_hover": "#e2e8f0",
        "bg_tooltip": "#1e293b",
        "text_primary": "#1e293b",
        "text_secondary": "#475569",
        "text_muted": "#94a3b8",
        "text_on_primary": "#ffffff",
        "primary": "#2563eb",
        "primary_hover": "#3b82f6",
        "primary_pressed": "#1d4ed8",
        "primary_light": "#dbeafe",
        "accent": "#0284c7",
        "success": "#16a34a",
        "warning": "#d97706",
        "danger": "#dc2626",
        "info": "#3b82f6",
        "border": "#e2e8f0",
        "border_light": "#cbd5e1",
        "border_focus": "#2563eb",
        "header_bg": "#ffffff",
        "header_text": "#1e293b",
        "header_border": "#2563eb",
        "scrollbar_bg": "#f1f5f9",
        "scrollbar_handle": "#cbd5e1",
        "scrollbar_hover": "#2563eb",
        "disabled_bg": "#f1f5f9",
        "disabled_text": "#94a3b8",
        "selection_bg": "#2563eb",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 15)",
    },

    "solarized_light": {
        "display_name": "سولارايزد فاتح (Solarized Light)",
        "icon": "fa5s.cloud-sun",
        "category": "light",
        "is_dark": False,
        "bg_main": "#fdf6e3",
        "bg_card": "#eee8d5",
        "bg_input": "#eee8d5",
        "bg_header": "#eee8d5",
        "bg_dialog": "#eee8d5",
        "bg_sidebar": "#fdf6e3",
        "bg_hover": "#e6dfcb",
        "bg_tooltip": "#073642",
        "text_primary": "#657b83",
        "text_secondary": "#586e75",
        "text_muted": "#93a1a1",
        "text_on_primary": "#fdf6e3",
        "primary": "#268bd2",
        "primary_hover": "#2aa198",
        "primary_pressed": "#0d6ebd",
        "primary_light": "#d0e8f5",
        "accent": "#2aa198",
        "success": "#859900",
        "warning": "#b58900",
        "danger": "#dc322f",
        "info": "#268bd2",
        "border": "#d3cbb7",
        "border_light": "#c4bcaa",
        "border_focus": "#268bd2",
        "header_bg": "#eee8d5",
        "header_text": "#657b83",
        "header_border": "#268bd2",
        "scrollbar_bg": "#eee8d5",
        "scrollbar_handle": "#c4bcaa",
        "scrollbar_hover": "#268bd2",
        "disabled_bg": "#fdf6e3",
        "disabled_text": "#93a1a1",
        "selection_bg": "#268bd2",
        "selection_text": "#fdf6e3",
        "shadow_color": "rgba(0, 0, 0, 10)",
    },

    "gruvbox_light": {
        "display_name": "جروفبوكس فاتح (Gruvbox Light)",
        "icon": "fa5s.seedling",
        "category": "light",
        "is_dark": False,
        "bg_main": "#fbf1c7",
        "bg_card": "#ebdbb2",
        "bg_input": "#ebdbb2",
        "bg_header": "#ebdbb2",
        "bg_dialog": "#ebdbb2",
        "bg_sidebar": "#fbf1c7",
        "bg_hover": "#e0cfa0",
        "bg_tooltip": "#282828",
        "text_primary": "#3c3836",
        "text_secondary": "#504945",
        "text_muted": "#928374",
        "text_on_primary": "#fbf1c7",
        "primary": "#458588",
        "primary_hover": "#83a598",
        "primary_pressed": "#076678",
        "primary_light": "#c8dfd0",
        "accent": "#689d6a",
        "success": "#79740e",
        "warning": "#b57614",
        "danger": "#cc241d",
        "info": "#458588",
        "border": "#d5c4a1",
        "border_light": "#bdae93",
        "border_focus": "#458588",
        "header_bg": "#ebdbb2",
        "header_text": "#3c3836",
        "header_border": "#458588",
        "scrollbar_bg": "#ebdbb2",
        "scrollbar_handle": "#bdae93",
        "scrollbar_hover": "#458588",
        "disabled_bg": "#fbf1c7",
        "disabled_text": "#928374",
        "selection_bg": "#458588",
        "selection_text": "#fbf1c7",
        "shadow_color": "rgba(0, 0, 0, 10)",
    },

    "catppuccin_latte": {
        "display_name": "كابتشينو فاتح (Catppuccin Latte)",
        "icon": "fa5s.mug-hot",
        "category": "light",
        "is_dark": False,
        "bg_main": "#eff1f5",
        "bg_card": "#e6e9ef",
        "bg_input": "#e6e9ef",
        "bg_header": "#e6e9ef",
        "bg_dialog": "#e6e9ef",
        "bg_sidebar": "#eff1f5",
        "bg_hover": "#dce0e8",
        "bg_tooltip": "#4c4f69",
        "text_primary": "#4c4f69",
        "text_secondary": "#5c5f77",
        "text_muted": "#9ca0b0",
        "text_on_primary": "#eff1f5",
        "primary": "#1e66f5",
        "primary_hover": "#4983f7",
        "primary_pressed": "#1652cc",
        "primary_light": "#cddcfc",
        "accent": "#8839ef",
        "success": "#40a02b",
        "warning": "#df8e1d",
        "danger": "#d20f39",
        "info": "#1e66f5",
        "border": "#ccd0da",
        "border_light": "#bcc0cc",
        "border_focus": "#1e66f5",
        "header_bg": "#e6e9ef",
        "header_text": "#4c4f69",
        "header_border": "#1e66f5",
        "scrollbar_bg": "#e6e9ef",
        "scrollbar_handle": "#bcc0cc",
        "scrollbar_hover": "#1e66f5",
        "disabled_bg": "#eff1f5",
        "disabled_text": "#9ca0b0",
        "selection_bg": "#1e66f5",
        "selection_text": "#eff1f5",
        "shadow_color": "rgba(0, 0, 0, 10)",
    },

    "cream": {
        "display_name": "كريمي (Cream)",
        "icon": "fa5s.spa",
        "category": "light",
        "is_dark": False,
        "bg_main": "#faf8f5",
        "bg_card": "#f0ece4",
        "bg_input": "#f0ece4",
        "bg_header": "#f0ece4",
        "bg_dialog": "#f0ece4",
        "bg_sidebar": "#faf8f5",
        "bg_hover": "#e5dfd5",
        "bg_tooltip": "#3d3929",
        "text_primary": "#3d3929",
        "text_secondary": "#5c5640",
        "text_muted": "#a09880",
        "text_on_primary": "#faf8f5",
        "primary": "#8b7355",
        "primary_hover": "#a0896e",
        "primary_pressed": "#705d44",
        "primary_light": "#e0d8c8",
        "accent": "#c49a6c",
        "success": "#6b8e23",
        "warning": "#d4a017",
        "danger": "#c0392b",
        "info": "#8b7355",
        "border": "#e0d8c8",
        "border_light": "#d0c8b8",
        "border_focus": "#8b7355",
        "header_bg": "#f0ece4",
        "header_text": "#3d3929",
        "header_border": "#8b7355",
        "scrollbar_bg": "#f0ece4",
        "scrollbar_handle": "#d0c8b8",
        "scrollbar_hover": "#8b7355",
        "disabled_bg": "#faf8f5",
        "disabled_text": "#a09880",
        "selection_bg": "#8b7355",
        "selection_text": "#faf8f5",
        "shadow_color": "rgba(0, 0, 0, 8)",
    },

    "lavender": {
        "display_name": "لافندر (Lavender)",
        "icon": "fa5s.feather",
        "category": "light",
        "is_dark": False,
        "bg_main": "#f5f0ff",
        "bg_card": "#ede5ff",
        "bg_input": "#ede5ff",
        "bg_header": "#ede5ff",
        "bg_dialog": "#ede5ff",
        "bg_sidebar": "#f5f0ff",
        "bg_hover": "#e0d5f5",
        "bg_tooltip": "#2d1b4e",
        "text_primary": "#2d1b4e",
        "text_secondary": "#4a3770",
        "text_muted": "#9b8cba",
        "text_on_primary": "#ffffff",
        "primary": "#7c3aed",
        "primary_hover": "#8b5cf6",
        "primary_pressed": "#6d28d9",
        "primary_light": "#ddd5f0",
        "accent": "#a78bfa",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "danger": "#ef4444",
        "info": "#7c3aed",
        "border": "#ddd5f0",
        "border_light": "#cdc2e8",
        "border_focus": "#7c3aed",
        "header_bg": "#ede5ff",
        "header_text": "#2d1b4e",
        "header_border": "#7c3aed",
        "scrollbar_bg": "#ede5ff",
        "scrollbar_handle": "#cdc2e8",
        "scrollbar_hover": "#7c3aed",
        "disabled_bg": "#f5f0ff",
        "disabled_text": "#9b8cba",
        "selection_bg": "#7c3aed",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 8)",
    },

    "mint": {
        "display_name": "نعناع (Mint)",
        "icon": "fa5s.leaf",
        "category": "light",
        "is_dark": False,
        "bg_main": "#f0faf5",
        "bg_card": "#e0f2eb",
        "bg_input": "#e0f2eb",
        "bg_header": "#e0f2eb",
        "bg_dialog": "#e0f2eb",
        "bg_sidebar": "#f0faf5",
        "bg_hover": "#c8e6d8",
        "bg_tooltip": "#1a3d2b",
        "text_primary": "#1a3d2b",
        "text_secondary": "#2d5e42",
        "text_muted": "#7db99a",
        "text_on_primary": "#ffffff",
        "primary": "#0d9488",
        "primary_hover": "#14b8a6",
        "primary_pressed": "#0a7c72",
        "primary_light": "#c8e6d8",
        "accent": "#2dd4bf",
        "success": "#22c55e",
        "warning": "#eab308",
        "danger": "#ef4444",
        "info": "#0d9488",
        "border": "#c8e6d8",
        "border_light": "#a8d6c0",
        "border_focus": "#0d9488",
        "header_bg": "#e0f2eb",
        "header_text": "#1a3d2b",
        "header_border": "#0d9488",
        "scrollbar_bg": "#e0f2eb",
        "scrollbar_handle": "#a8d6c0",
        "scrollbar_hover": "#0d9488",
        "disabled_bg": "#f0faf5",
        "disabled_text": "#7db99a",
        "selection_bg": "#0d9488",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 8)",
    },

    "peach": {
        "display_name": "خوخي (Peach)",
        "icon": "fa5s.heart",
        "category": "light",
        "is_dark": False,
        "bg_main": "#fff5f0",
        "bg_card": "#ffe8dd",
        "bg_input": "#ffe8dd",
        "bg_header": "#ffe8dd",
        "bg_dialog": "#ffe8dd",
        "bg_sidebar": "#fff5f0",
        "bg_hover": "#f5d0c0",
        "bg_tooltip": "#4a2520",
        "text_primary": "#4a2520",
        "text_secondary": "#6d3a32",
        "text_muted": "#c08878",
        "text_on_primary": "#ffffff",
        "primary": "#f97316",
        "primary_hover": "#fb923c",
        "primary_pressed": "#ea580c",
        "primary_light": "#f5d0c0",
        "accent": "#fb923c",
        "success": "#22c55e",
        "warning": "#eab308",
        "danger": "#ef4444",
        "info": "#f97316",
        "border": "#f5d0c0",
        "border_light": "#e8b8a8",
        "border_focus": "#f97316",
        "header_bg": "#ffe8dd",
        "header_text": "#4a2520",
        "header_border": "#f97316",
        "scrollbar_bg": "#ffe8dd",
        "scrollbar_handle": "#e8b8a8",
        "scrollbar_hover": "#f97316",
        "disabled_bg": "#fff5f0",
        "disabled_text": "#c08878",
        "selection_bg": "#f97316",
        "selection_text": "#ffffff",
        "shadow_color": "rgba(0, 0, 0, 8)",
    },
}


def get_palette(theme_name: str) -> dict:
    """Get palette for a theme. Falls back to dark."""
    return THEME_PALETTES.get(theme_name, THEME_PALETTES["dark"])


def get_all_theme_names() -> list:
    """Get all available theme names."""
    return list(THEME_PALETTES.keys())


def get_dark_themes() -> list:
    """Get names of dark themes."""
    return [k for k, v in THEME_PALETTES.items() if v["is_dark"]]


def get_light_themes() -> list:
    """Get names of light themes."""
    return [k for k, v in THEME_PALETTES.items() if not v["is_dark"]]
